name: bondnet document01
favicon: null
layout_spectrum: 0.51594
typography_spectrum: 0.38941
title: bondnet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72020501-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bca887'
    - '#c9c5b0'
    - '#a89779'
    - '#eae8a5'
    - '#ded79a'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
