name: bondnet document01
favicon: null
layout_spectrum: 0.8955077580176294
typography_spectrum: 0.5995382971595973
title: bondnet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5176718607544899
  lightness: 0.5451845522038639
  saturation: 0.2417680525686592
  rhythmicContrast: 0.8371387245133519
purpose: []
