name: bondnet document01
favicon: null
layout_spectrum: 0.82364
typography_spectrum: 0.38941
title: bondnet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72020501-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BCA887'
    - '#C9C5B0'
    - '#A89779'
    - '#EAE8A5'
    - '#DED79A'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
