analytics:
  google: UA-72020501-1
color:
  brandColors:
    - '#BCA887'
    - '#C9C5B0'
    - '#A89779'
    - '#EAE8A5'
    - '#DED79A'
  brandStrength: 0.757473
  lightness: 0.5625
  rhythmicContrast: 0.25
  saturation: 0.4375
cta: {}
layout_spectrum: 0.639946
name: bondnet document01
opengraph: {}
purpose: []
typography_spectrum: 0.38941
